modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="newgenstory_fanatic_version"
version="1.0.0"
displayName="NewGenStory Fanatic Version"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kazmur, MCreator"

[[dependencies.newgenstory_fanatic_version]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




